export const FETCH_HIGHLIGHTS = 'FETCH_HIGHLIGHTS';
export const FETCH_HIGHLIGHTS_SUCCESS = 'FETCH_HIGHLIGHTS_SUCCESS';
export const FETCH_HIGHLIGHTS_EMPTY = 'FETCH_HIGHLIGHTS_EMPTY';
export const FETCH_HIGHLIGHTS_FAIL = 'FETCH_HIGHLIGHTS_FAIL';

export const FETCH_BUYERS = 'FETCH_BUYERS';
export const FETCH_BUYERS_SUCCESS = 'FETCH_BUYERS_SUCCESS';
export const FETCH_BUYERS_EMPTY = 'FETCH_BUYERS_EMPTY';
export const FETCH_BUYERS_FAIL = 'FETCH_BUYERS_FAIL';

export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_EMPTY = 'FETCH_COUNTRIES_EMPTY';
export const FETCH_COUNTRIES_FAIL = 'FETCH_COUNTRIES_FAIL';

export const FETCH_INCOME = 'FETCH_INCOME';
export const FETCH_INCOME_SUCCESS = 'FETCH_INCOME_SUCCESS';
export const FETCH_INCOME_EMPTY = 'FETCH_INCOME_EMPTY';
export const FETCH_INCOME_FAIL = 'FETCH_INCOME_FAIL';